# Generated by Django 2.0.2 on 2018-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
