# Generated by Django 2.0.2 on 2018-03-22 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ORDERID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('time_placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('order_status', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Items')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Client')),
            ],
        ),
    ]
