# Generated by Django 2.0.2 on 2018-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Items',
            field=models.ManyToManyField(default=None, null=True, to='restaurant.Items'),
        ),
    ]
