# Generated by Django 2.0.2 on 2018-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180405_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Items',
            field=models.ManyToManyField(to='restaurant.Items'),
        ),
    ]
